apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fedprivacylab-data-pvc
  namespace: fedprivacylab
  labels:
    app: fedprivacylab
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
